# Candidate roster: matched text + math families.
# Each entry: key, label, lineage note, text font files, math font file, category.
TEXMF = "/usr/share/texlive/texmf-dist/fonts/opentype/public/"
TEXMF2 = "/usr/share/texmf/fonts/opentype/public/"
TM2 = TEXMF2
ADF = "/usr/share/fonts/truetype/adf/"
NEO = "/usr/share/fonts/opentype/neohellenic/"
CMU = "/usr/share/fonts/truetype/cmu/"

ROSTER = [
 dict(key="newcm", label="New Computer Modern", lineage="Knuth's Computer Modern, redrawn and extended (Tsolomitis)",
      cat="serif", path=TEXMF+"newcomputermodern/",
      up="NewCM10-Regular.otf", it="NewCM10-Italic.otf", bf="NewCM10-Bold.otf", bfit="NewCM10-BoldItalic.otf",
      sans_path=TEXMF+"newcomputermodern/", sans="NewCMSans10-Regular.otf",
      math=TEXMF+"newcomputermodern/NewCMMath-Regular.otf"),
 dict(key="lmodern", label="Latin Modern", lineage="The classic LaTeX default, Computer Modern in OpenType",
      cat="serif", path=TM2+"lm/", up="lmroman10-regular.otf", it="lmroman10-italic.otf",
      bf="lmroman10-bold.otf", bfit="lmroman10-bolditalic.otf",
      sans_path=TM2+"lm/", sans="lmsans10-regular.otf",
      math=TM2+"lm-math/latinmodern-math.otf"),
 dict(key="stixtwo", label="STIX Two", lineage="Commissioned by scientific publishers; Times-adjacent",
      cat="serif", path=TEXMF+"stix2-otf/", up="STIXTwoText-Regular.otf", it="STIXTwoText-Italic.otf",
      bf="STIXTwoText-Bold.otf", bfit="STIXTwoText-BoldItalic.otf",
      sans_path=TEXMF+"fira/", sans="FiraSans-Regular.otf",
      math=TEXMF+"stix2-otf/STIXTwoMath-Regular.otf"),
 dict(key="pagella", label="TeX Gyre Pagella", lineage="Palatino (Zapf) — humanist, calligraphic",
      cat="serif", path=TM2+"tex-gyre/", up="texgyrepagella-regular.otf", it="texgyrepagella-italic.otf",
      bf="texgyrepagella-bold.otf", bfit="texgyrepagella-bolditalic.otf",
      sans_path=TM2+"tex-gyre/", sans="texgyreheros-regular.otf",
      math=TEXMF2+"tex-gyre-math/texgyrepagella-math.otf"),
 dict(key="termes", label="TeX Gyre Termes", lineage="Times New Roman — the journal default",
      cat="serif", path=TM2+"tex-gyre/", up="texgyretermes-regular.otf", it="texgyretermes-italic.otf",
      bf="texgyretermes-bold.otf", bfit="texgyretermes-bolditalic.otf",
      sans_path=TM2+"tex-gyre/", sans="texgyreheros-regular.otf",
      math=TEXMF2+"tex-gyre-math/texgyretermes-math.otf"),
 dict(key="schola", label="TeX Gyre Schola", lineage="Century Schoolbook — built for legibility at small size",
      cat="serif", path=TM2+"tex-gyre/", up="texgyreschola-regular.otf", it="texgyreschola-italic.otf",
      bf="texgyreschola-bold.otf", bfit="texgyreschola-bolditalic.otf",
      sans_path=TM2+"tex-gyre/", sans="texgyreheros-regular.otf",
      math=TEXMF2+"tex-gyre-math/texgyreschola-math.otf"),
 dict(key="bonum", label="TeX Gyre Bonum", lineage="Bookman — sturdy, wide, high x-height",
      cat="serif", path=TM2+"tex-gyre/", up="texgyrebonum-regular.otf", it="texgyrebonum-italic.otf",
      bf="texgyrebonum-bold.otf", bfit="texgyrebonum-bolditalic.otf",
      sans_path=TM2+"tex-gyre/", sans="texgyreadventor-regular.otf",
      math=TEXMF2+"tex-gyre-math/texgyrebonum-math.otf"),
 dict(key="libertinus", label="Libertinus", lineage="Linux Libertine redrawn (Hosny) — Wikipedia's old wordmark face",
      cat="serif", path=TEXMF+"libertinus-fonts/", up="LibertinusSerif-Regular.otf", it="LibertinusSerif-Italic.otf",
      bf="LibertinusSerif-Bold.otf", bfit="LibertinusSerif-BoldItalic.otf",
      sans_path=TEXMF+"libertinus-fonts/", sans="LibertinusSans-Regular.otf",
      math=TEXMF+"libertinus-fonts/LibertinusMath-Regular.otf"),
 dict(key="ebgaramond", label="EB Garamond", lineage="Granjon/Garamond revival — old-style, low x-height",
      cat="serif", path="/usr/share/fonts/truetype/ebgaramond/", up="EBGaramond12-Regular.ttf", it="EBGaramond12-Italic.ttf",
      bf="EBGaramond12-Regular.ttf", bfit="EBGaramond12-Italic.ttf",
      sans_path=TEXMF+"fira/", sans="FiraSans-Regular.otf",
      math=TEXMF+"garamond-math/Garamond-Math.otf"),
 dict(key="xcharter", label="XCharter", lineage="Bitstream Charter (Carter) — engineered for low-res output",
      cat="serif", path=TEXMF+"xcharter/", up="XCharter-Roman.otf", it="XCharter-Italic.otf",
      bf="XCharter-Bold.otf", bfit="XCharter-BoldItalic.otf",
      sans_path=TEXMF+"fira/", sans="FiraSans-Regular.otf",
      math=TEXMF+"xcharter-math/XCharter-Math.otf"),
 dict(key="erewhon", label="Erewhon", lineage="Utopia (Slimbach) derivative — transitional, sturdy",
      cat="serif", path=TEXMF+"erewhon/", up="Erewhon-Regular.otf", it="Erewhon-Italic.otf",
      bf="Erewhon-Bold.otf", bfit="Erewhon-BoldItalic.otf",
      sans_path=TEXMF+"fira/", sans="FiraSans-Regular.otf",
      math=TEXMF+"erewhon-math/Erewhon-Math.otf"),
 dict(key="kproman", label="Kp-Fonts Roman", lineage="Kepler-flavoured (Caignaert) — a complete in-house family",
      cat="serif", path=TEXMF+"kpfonts-otf/", up="KpRoman-Regular.otf", it="KpRoman-Italic.otf",
      bf="KpRoman-Bold.otf", bfit="KpRoman-BoldItalic.otf",
      sans_path=TEXMF+"kpfonts-otf/", sans="KpSans-Regular.otf",
      math=TEXMF+"kpfonts-otf/KpMath-Regular.otf"),
 dict(key="oldstandard", label="Old Standard", lineage="Early-20th-century scholarly printing revival",
      cat="serif", path=TEXMF+"oldstandard/", up="OldStandard-Regular.otf", it="OldStandard-Italic.otf",
      bf="OldStandard-Bold.otf", bfit="OldStandard-Italic.otf",
      sans_path=TEXMF+"fira/", sans="FiraSans-Regular.otf",
      math=TEXMF+"oldstandard/OldStandard-Math.otf"),
 dict(key="berenis", label="BerenisADF Pro", lineage="Arkandis' Baskerville-meets-Garamond original",
      cat="serif", path="/usr/share/fonts/truetype/adf/", up="BerenisADFPro-Regular.otf", it="BerenisADFPro-Italic.otf",
      bf="BerenisADFPro-Bold.otf", bfit="BerenisADFPro-BoldItalic.otf",
      sans_path=TEXMF+"fira/", sans="FiraSans-Regular.otf",
      math=ADF+"BerenisADFProMath-Regular.otf"),
 dict(key="concrete", label="Concrete + Euler", lineage="Knuth's Concrete Roman with Zapf's Euler math",
      cat="serif", path="/usr/share/fonts/truetype/cmu/", up="cmunorm.ttf", it="cmunoti.ttf",
      bf="cmunobx.ttf", bfit="cmunobi.ttf",
      sans_path=TM2+"lm/", sans="lmsans10-regular.otf",
      math=TEXMF+"euler-math/Euler-Math.otf"),
 dict(key="dejavu", label="DejaVu Serif", lineage="Vera-derived screen face; very large x-height",
      cat="serif", path="/usr/share/fonts/truetype/dejavu/", up="DejaVuSerif.ttf", it="DejaVuSerif-Italic.ttf",
      bf="DejaVuSerif-Bold.ttf", bfit="DejaVuSerif-BoldItalic.ttf",
      sans_path="/usr/share/fonts/truetype/dejavu/", sans="DejaVuSans.ttf",
      math=TEXMF2+"tex-gyre-math/texgyredejavu-math.otf"),
 dict(key="fira", label="Fira Sans + Fira Math", lineage="Mozilla's UI face with a purpose-built sans math font",
      cat="sans", path=TEXMF+"fira/", up="FiraSans-Regular.otf", it="FiraSans-Italic.otf",
      bf="FiraSans-Bold.otf", bfit="FiraSans-BoldItalic.otf",
      sans_path=TEXMF+"fira/", sans="FiraSans-Regular.otf",
      math=TEXMF+"firamath/FiraMath-Regular.otf"),
 dict(key="kpsans", label="Kp-Fonts Sans", lineage="The rare sans family with a full matching sans math font",
      cat="sans", path=TEXMF+"kpfonts-otf/", up="KpSans-Regular.otf", it="KpSans-Italic.otf",
      bf="KpSans-Bold.otf", bfit="KpSans-BoldItalic.otf",
      sans_path=TEXMF+"kpfonts-otf/", sans="KpSans-Regular.otf",
      math=TEXMF+"kpfonts-otf/KpMath-Sans.otf"),
 dict(key="neohellenic", label="GFS Neohellenic", lineage="Greek-first humanist sans, with matching math",
      cat="sans", path=NEO, up="GFSNeohellenic.otf", it="GFSNeohellenicIt.otf",
      bf="GFSNeohellenicBold.otf", bfit="GFSNeohellenicBoldIt.otf",
      sans_path=NEO, sans="GFSNeohellenic.otf",
      math=TEXMF+"gfsneohellenicmath/GFSNeohellenicMath.otf"),
]
